[book]
authors = ["HStudio"]
language = "en"
multilingual = false
src = "docs"
title = "HStudio Document"

[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/HStudioDiscordBot/Document"
edit-url-template = "https://github.com/HStudioDiscordBot/Document/edit/main/{path}"